application: civil-empire-796
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:  
- url: /.*
  script: finalproject.application

  
libraries:
- name: webapp2
  version: latest
- name: django
  version: latest